# ==========================
# MineSteal Configuration
# ==========================

# Core hearts settings
settings:
  # Vanilla is 2 HP per heart. Leave at 2 unless you know why to change it.
  hp-per-heart: 2

  # Bounds (in full hearts)
  minimum-hearts: 5
  max-hearts: 40

  # Lifesteal rules (per player-vs-player kill/death)
  gain-on-kill: 1          # hearts the killer gains when auto-transfer = true
  lose-on-death: 1         # hearts the victim loses (never below minimum-hearts)

# Death behavior
death:
  # Victim-side behavior
  drop-hearts-on-death: true   # true = drop heart item(s) on the ground
  auto-transfer: false         # true = grant hearts directly to killer instead of dropping

  # Permanent deathban behavior when a player reaches minimum-hearts
  deathban:
    enabled: true
    mode: SPECTATOR            # SPECTATOR = soft deathban until revived; BAN = permanent server ban
    reason: "Out of hearts"
    # Only used when mode=BAN (permanent, no duration)
    ban_command: "litebans:ban %player% Out of hearts"

# Heart item (consumable that adds +1 heart)
heart_item:
  name: "&cHeart"
  lore:
    - "&7Right-click to consume"
    - "&7and gain &c+1 &7max heart."
  refuse_if_at_cap: true

# Heart Shards (used to craft Heart)
heart_shard:
  enabled: true
  name: "&dHeart Shard"
  lore:
    - "&7Collect 9 to craft a &cHeart"
    - "&7Drop from bosses & elites"
  craft_heart_from_9_shards: true
  recipe_type: SHAPED     # SHAPED or SHAPELESS

  # Reverse: 1 Heart -> N Shards
  reverse_recipe:
    enabled: false
    type: SHAPELESS       # SHAPED or SHAPELESS
    output: 9             # how many shards you get from 1 heart

# PvE shard drops (per-entity)
pve_drops:
  enabled: true
  entities:
    WARDEN:         { chance: 1.0,  min: 2, max: 4 }
    WITHER:         { chance: 1.0,  min: 2, max: 3 }
    ENDER_DRAGON:   { chance: 1.0,  min: 3, max: 5 }
    ELDER_GUARDIAN: { chance: 0.65, min: 1, max: 2 }
    RAVAGER:        { chance: 0.45, min: 1, max: 2 }
    PILLAGER:       { chance: 0.10, min: 1, max: 1 }

# Cooldowns
cooldowns:
  consume: 5                # seconds between consuming heart items
  withdraw: 2               # seconds between /hearts withdraw
  request_revive: 60        # seconds between /hearts request_revive
  gui_click_ms: 150         # GUI anti-spam (milliseconds)

# Leaderboard (chat + scope)
leaderboard:
  page_size: 10
  include_offline: true
  online_world_only: false
  name_color_by_team: true
  chat_hover_show:
    - "&7UUID: &f%uuid%"
    - "&7Hearts: &c%hearts%"
  chat_click_action: "GUI"  # GUI or NONE

# DecentHolograms settings (auto-refreshed in the background)
holograms:
  enabled: true
  id_prefix: "ms_top"            # Only holograms with this prefix are auto-refreshed
  update_period_seconds: 20
  default_size: 10
  default_page: 1
  header: "&cTop Hearts &7(Page %page%)"
  entry:  "&c#%rank% &7%name%: &c%hearts%"

# Storage (single YAML file under plugins/MineSteal/data/players.yml)
storage:
  single-file: true

# Messages
messages:
  prefix: "&c[MineSteal]&r "
  self_hearts: "&7You have &c%hearts%&7/&c%max% &7hearts."
  added: "&7Gave &c%amount% &7heart(s) to &c%player%&7 (&c%new%&7 total)."
  removed: "&7Removed &c%amount% &7heart(s) from &c%player%&7 (&c%new%&7 total)."
  set: "&7Set &c%player%&7 hearts to &c%new%&7."
  at_cap: "&7You're already at the heart cap (&c%max%&7)."
  cannot_consume: "&7You can't consume this now."
  revived: "&7Revived &c%player%&7."
  reloaded: "&7Config reloaded."
  cooldown_consume: "&7You must wait &c%seconds%s&7 before consuming another Heart."
  cooldown_withdraw: "&7You must wait &c%seconds%s&7 before withdrawing again."
  cooldown_request_revive: "&7You must wait &c%seconds%s&7 before requesting revive again."
  top_header: "&cTop Hearts &7(Page %page%):"
  top_line: "&c#%rank% &7%name%: &c%hearts%&7 hearts"
  top_empty: "&7No entries."

# Withdraw behavior (command & GUI)
withdraw:
  withdraw-as-shards: false   # true = give shards instead of heart items
  shards_per_heart: 9         # how many shards represent one heart

# Revive Token (players can revive others)
revive_token:
  enabled: true
  material: NETHER_STAR
  name: "&aRevive Token"
  lore:
    - "&7Use to revive a deathbanned player."
  consume_on_use: true

  # If true, players must have this permission to use token or /revive
  require_permission: false
  permission: "minesteal.revive.use"

  # Allow self-revive with a token (spectator only)
  allow_self: false

  # Used by /revive when death.deathban.mode=BAN (permanent unban)
  unban_command: "litebans:unban %player%"

  # Optional crafting recipe for the token
  recipe:
    enabled: false
    type: SHAPED              # SHAPED or SHAPELESS
    # For SHAPED: 3 rows of 3 characters (H = Heart, S = Shard, W = Extra Material)
    shape:
      - "HSH"
      - "SWS"
      - "HSH"
    # For SHAPELESS: how many shards required (plus 1 Heart + 1 Extra Material)
    shapeless:
      shards: 4
    # The extra vanilla material required (mapped to 'W' above)
    extra_material: NETHER_STAR

  # PvE token drops (optional)
  drops:
    enabled: true
    entities:
      ENDER_DRAGON:   { chance: 0.25, min: 1, max: 2 }
      WITHER:         { chance: 0.15, min: 1, max: 1 }
      WARDEN:         { chance: 0.10, min: 1, max: 1 }
      ELDER_GUARDIAN: { chance: 0.05, min: 1, max: 1 }

